### ISSUE TITLE
Error:(2) Attribute "textColor" has already been defined

### ISSUE THREAD

**Issue by mori-honest** [jakob-grabner/Circle-Progress-View#16] opened 2015-09-30 09:39 UTC
also : Error:(2) Attribute "fillColor" has already been defined

**Comment by jakob-grabner** [comment] 2015-09-30 10:12
It seems you have a naming conflict with another library. Could you post the entire stack trace or the list of libraries you use. This would help.

**Comment by jakob-grabner** [comment] 2015-09-30 14:28
Please check out the latest release, i prefixed all attributes with "cpv_". Your problem should be fixed now.

**Comment by mori-honest** [comment] 2015-10-01 07:21
Thank you, i'll check the solution and let you know that if it is working or not.

**Comment by KimmiDhingra1991** [comment] 2015-10-16 07:28
Thanks jakob for this library, Actually I got some issues in hdpi devices
When there is not enough space, Then contour size not set as defined in xml, And there is also padding around the view.  Please check screenshot, I set contour size in xml is 1, but it doesn't make effect on the view
However, its working fine in xhdpi and xxhdpi
I think the only problem is spacing, 
![circular progressview](https://cloud.githubusercontent.com/assets/6429500/10535907/6fb57cf4-7404-11e5-94bf-9b83c7ec3e89.png)

**Comment by jakob-grabner** [comment] 2015-10-16 09:21
Hi, I am not sure what the problem is. Could you add two screenshots, one showing the result you want to achieve (so on an xhdpi device) and one showing the error.

Also i just fixed the margin error, see issue #19.

**Closed** 2015-11-13 08:32 UTC
